# 5 numpy.array 基本操作

In [3]:
import numpy as np

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
X = np.arange(15).reshape((3, 5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性: ndim-维数  shape-行列  size-元素个数

In [6]:
x.ndim

1

In [7]:
X.ndim

2

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size

10

In [11]:
X.size

15

## numpy.array 访问元素

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [15]:
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
x[1:8:2]

array([1, 3, 5, 7])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x[-1]

9

In [22]:
x[-1:]

array([9])

In [16]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
X[0][0]

0

In [25]:
X[0, 0]

0

In [17]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [18]:
X[0:5:2,:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [28]:
X[0]

array([0, 1, 2, 3, 4])

In [29]:
X[0, :]

array([0, 1, 2, 3, 4])

In [31]:
subX = X[:2, :3]  # 子矩阵相当于原矩阵的引用
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X  

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [36]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [40]:
subX = X[:2, :3].copy()  # 创建一个和原矩阵无关的矩阵
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [42]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x.ndim

1

In [7]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
A = x.reshape(10,)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
np.reshape?

In [14]:
A = x.reshape(5, -1)

In [15]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
A = x.reshape(-1, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
A = x.reshape(2)
A

ValueError: cannot reshape array of size 10 into shape (2,)

In [55]:
A = x.reshape(3, 5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [56]:
x.reshape(2, 4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [38]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
np.reshape(a, 8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
np.reshape(a,(2,-1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])