## 聚合操作

In [9]:
import numpy as np
L = np.random.random(100)
L

array([0.576632  , 0.80900079, 0.08281461, 0.34980655, 0.52167427,
       0.99987636, 0.68960899, 0.03458789, 0.39050899, 0.86946969,
       0.93555044, 0.98513358, 0.99325914, 0.72448272, 0.43416964,
       0.82123498, 0.18246347, 0.67916989, 0.08160303, 0.03733145,
       0.51117778, 0.72283555, 0.98342501, 0.8696809 , 0.67511324,
       0.21131324, 0.26917414, 0.37491295, 0.78162815, 0.76791121,
       0.15834168, 0.24650555, 0.51999369, 0.34429224, 0.58155297,
       0.88058442, 0.91165133, 0.41171021, 0.59986605, 0.00654301,
       0.16836017, 0.47987489, 0.45038452, 0.60177871, 0.46446055,
       0.02459007, 0.47118498, 0.85563095, 0.31699215, 0.09926812,
       0.57950645, 0.03544054, 0.28528152, 0.27486659, 0.01029595,
       0.88275323, 0.10995774, 0.35949743, 0.58618402, 0.58400211,
       0.19620903, 0.06229035, 0.40713381, 0.08306418, 0.41323256,
       0.98054272, 0.75107315, 0.79929884, 0.82895061, 0.38832265,
       0.2446321 , 0.1927334 , 0.80831618, 0.04613139, 0.49756

In [10]:
sum(L)

48.129356969973564

In [11]:
np.sum(L)

48.12935696997356

In [42]:
big_arr = np.random.rand(1000000)
%timeit sum(big_arr)
%timeit np.sum(big_arr)
%timeit big_arr.sum()

99.5 ms ± 543 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.18 ms ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.18 ms ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
np.min(big_arr)

4.2499184615962804e-07

In [37]:
np.max(big_arr)

0.9999991570992679

In [39]:
big_arr.min()

4.2499184615962804e-07

In [40]:
big_arr.sum()

499872.0470461095

In [43]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.sum(X)

120

In [45]:
np.sum(X, axis=0)  # 每一列的和

array([24, 28, 32, 36])

In [46]:
np.sum(X, axis=1)  # 每一行的和

array([ 6, 22, 38, 54])

In [47]:
np.min(X)

0

In [49]:
np.min(X, axis=0)

array([0, 1, 2, 3])

In [50]:
np.prod(X)  # 所有元素的乘积

0

In [52]:
np.prod(X + 1)  # product 乘积

2004189184

In [53]:
np.mean(X)   # 平均值

7.5

In [54]:
np.median(X)  # 中位数

7.5

In [70]:
np.percentile(big_arr, 50)  # 计算50%位的数

0.49854635556934335

In [56]:
np.median(big_arr)

0.49854635556934335

In [57]:
np.percentile(big_arr, 100)

0.9999984263222798

In [58]:
np.max(big_arr)

0.9999984263222798

In [61]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_arr, q=percent))

7.288633452340321e-08
0.24932697519948022
0.49854635556934335
0.7491862533459003
0.9999984263222798


In [62]:
np.var(big_arr)  # 方差 variance

0.08329042805299676

In [63]:
np.std(big_arr) # 标准差 standard deviation

0.28860081090148854

In [65]:
x = np.random.normal(0, 1, size=1000000)

In [66]:
np.mean(x)

0.001564875364152057

In [68]:
np.var(x)

1.0000655807958367

In [71]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
np.percentile(x, 13)

1.9500000000000002